<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Route as RouteFacade;

class ApiContractSnapshotCommand extends Command
{
    protected $signature = 'api:contract-snapshot
        {--write : Write the current API contract snapshot}
        {--path=docs/api-contract.snapshot : Snapshot file path relative to project root}';

    protected $description = 'Check or write API route contract snapshot to detect breaking changes';

    public function handle(): int
    {
        $snapshotPath = base_path(trim((string) $this->option('path')));
        $actual = $this->collectRouteSignatures();

        if ((bool) $this->option('write')) {
            File::ensureDirectoryExists(dirname($snapshotPath));
            File::put($snapshotPath, $this->renderSnapshot($actual));
            $this->info('API contract snapshot updated: '.$snapshotPath);

            return self::SUCCESS;
        }

        if (! File::exists($snapshotPath)) {
            $this->error('API contract snapshot is missing: '.$snapshotPath);
            $this->line('Run: php artisan api:contract-snapshot --write');

            return self::FAILURE;
        }

        $expected = $this->parseSnapshot((string) File::get($snapshotPath));
        if ($expected === $actual) {
            $this->info('API contract snapshot is up to date.');

            return self::SUCCESS;
        }

        $removed = array_values(array_diff($expected, $actual));
        $added = array_values(array_diff($actual, $expected));

        $this->error('API contract snapshot mismatch detected.');
        if ($removed !== []) {
            $this->warn('Routes removed from current app (present in snapshot):');
            foreach (array_slice($removed, 0, 20) as $entry) {
                $this->line('  - '.$entry);
            }
        }
        if ($added !== []) {
            $this->warn('New routes not tracked in snapshot:');
            foreach (array_slice($added, 0, 20) as $entry) {
                $this->line('  + '.$entry);
            }
        }

        $this->line('If intentional, run: php artisan api:contract-snapshot --write');

        return self::FAILURE;
    }

    /**
     * @return list<string>
     */
    private function collectRouteSignatures(): array
    {
        $signatures = [];
        $routes = RouteFacade::getRoutes()->getRoutes();

        foreach ($routes as $route) {
            $uri = ltrim($route->uri(), '/');
            if (! str_starts_with($uri, 'api/')) {
                continue;
            }

            $methods = array_values(
                array_filter(
                    $route->methods(),
                    static fn (string $method): bool => ! in_array($method, ['HEAD', 'OPTIONS'], true)
                )
            );

            sort($methods);

            foreach ($methods as $method) {
                $signatures[] = sprintf('%s %s', strtoupper($method), $uri);
            }
        }

        $signatures = array_values(array_unique($signatures));
        sort($signatures);

        return $signatures;
    }

    /**
     * @return list<string>
     */
    private function parseSnapshot(string $content): array
    {
        $lines = preg_split('/\R/', $content) ?: [];
        $entries = [];

        foreach ($lines as $line) {
            $trimmed = trim($line);
            if ($trimmed === '' || str_starts_with($trimmed, '#')) {
                continue;
            }

            $entries[] = $trimmed;
        }

        $entries = array_values(array_unique($entries));
        sort($entries);

        return $entries;
    }

    /**
     * @param  list<string>  $signatures
     */
    private function renderSnapshot(array $signatures): string
    {
        $header = [
            '# API route contract snapshot',
            '# Generated by: php artisan api:contract-snapshot --write',
            '# Keep this file in version control and review diffs as API contract changes.',
            '',
        ];

        return implode(PHP_EOL, array_merge($header, $signatures, ['']));
    }
}
